# Plant database for zones 5a through 9b
# native_regions: list of US regions where the plant is actually native
#   regions: southwest, great_plains, northeast, southeast, midwest, northwest, california
# water: low / medium / high
# days_to_maturity: approximate days from transplant (or seed where noted)

PLANTS = [
    # --- VEGETABLES ---
    {
        "name": "Green Chile Pepper",
        "category": "vegetable",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "medium",
        "days_to_maturity": 80,
        "notes": "Staple of NM cuisine. Start indoors 8 weeks before last frost.",
        "direct_sow": False,
        "weeks_before_frost": 8,
        "companions": [
            {"name": "Basil", "reason": "repels aphids and spider mites"},
            {"name": "Carrot", "reason": "loosens soil around pepper roots"},
            {"name": "Tomato", "reason": "similar needs, mutual pest confusion"},
            {"name": "Epazote", "reason": "traditional companion, deters pests"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic, inhibits pepper growth"},
            {"name": "Brassicas", "reason": "compete for nutrients and water"},
        ],
    },
    {
        "name": "Pinto Bean",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 90,
        "notes": "Heat tolerant. Direct sow after last frost.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Corn (Heirloom Blue)", "reason": "Three Sisters - corn provides trellis support"},
            {"name": "Squash (Cushaw)", "reason": "Three Sisters - squash shades soil and suppresses weeds"},
            {"name": "Desert Marigold", "reason": "deters Mexican bean beetles"},
            {"name": "Epazote", "reason": "traditional companion - reduces bean flatulence, deters beetles"},
        ],
        "avoid": [
            {"name": "Onion", "reason": "alliums stunt bean growth"},
            {"name": "Garlic", "reason": "inhibits bean germination and growth"},
            {"name": "Fennel", "reason": "allelopathic to most vegetables including beans"},
        ],
    },
    {
        "name": "Tomato",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 70,
        "notes": "Start indoors 6-8 weeks before last frost. Mulch heavily in NM heat.",
        "direct_sow": False,
        "weeks_before_frost": 8,
        "companions": [
            {"name": "Basil", "reason": "repels aphids and tomato hornworm, said to improve flavor"},
            {"name": "Carrot", "reason": "loosens soil around tomato roots"},
            {"name": "Desert Marigold", "reason": "deters nematodes and whiteflies"},
            {"name": "Borage", "reason": "deters tomato hornworm and attracts pollinators"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "strongly inhibits tomato growth"},
            {"name": "Corn (Heirloom Blue)", "reason": "share earworm/fruitworm pest"},
            {"name": "Brassicas", "reason": "compete for nutrients, different soil preferences"},
        ],
    },
    {
        "name": "Zucchini",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 50,
        "notes": "Direct sow after last frost. Very productive in high desert.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Corn (Heirloom Blue)", "reason": "Three Sisters - corn provides wind shelter"},
            {"name": "Pinto Bean", "reason": "Three Sisters - beans fix nitrogen"},
            {"name": "Nasturtium", "reason": "trap crop for aphids and squash bugs"},
            {"name": "Desert Marigold", "reason": "deters squash beetles and nematodes"},
        ],
        "avoid": [
            {"name": "Potato", "reason": "both susceptible to blight, shared disease risk"},
            {"name": "Fennel", "reason": "allelopathic to squash family"},
        ],
    },
    {
        "name": "Garlic",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 240,
        "notes": "Plant cloves in fall (Oct-Nov) for summer harvest.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Tomato", "reason": "deters spider mites and aphids on tomato"},
            {"name": "Beet", "reason": "mutual growth enhancement"},
            {"name": "Chamomile", "reason": "said to improve garlic flavor"},
            {"name": "Yarrow", "reason": "attracts beneficial insects to the bed"},
        ],
        "avoid": [
            {"name": "Pinto Bean", "reason": "garlic inhibits bean growth"},
            {"name": "Snap Pea", "reason": "alliums stunt pea growth"},
            {"name": "Black Bean", "reason": "garlic inhibits all legumes"},
        ],
    },
    {
        "name": "Kale",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northwest"],
        "water": "medium",
        "days_to_maturity": 55,
        "notes": "Cold hardy. Can overwinter in zone 6b with light protection.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
        "companions": [
            {"name": "Chamomile", "reason": "improves brassica growth and flavor"},
            {"name": "Nasturtium", "reason": "trap crop for aphids away from kale"},
            {"name": "Desert Marigold", "reason": "deters cabbage moths and loopers"},
            {"name": "Dill", "reason": "attracts beneficial wasps that prey on cabbage worms"},
        ],
        "avoid": [
            {"name": "Strawberry", "reason": "brassicas inhibit strawberry growth"},
            {"name": "Tomato", "reason": "compete for calcium, different watering rhythms"},
            {"name": "Fennel", "reason": "allelopathic to brassicas"},
        ],
    },
    {
        "name": "Corn (Heirloom Blue)",
        "category": "vegetable",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest", "great_plains", "midwest", "northeast", "southeast"],
        "water": "medium",
        "days_to_maturity": 100,
        "notes": "Traditional Pueblo crop. Direct sow in blocks for pollination.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Pinto Bean", "reason": "Three Sisters - beans fix nitrogen for corn"},
            {"name": "Squash (Cushaw)", "reason": "Three Sisters - squash leaves shade weeds"},
            {"name": "Sunflower", "reason": "attracts pollinators, similar height compatibility"},
            {"name": "Cucumber", "reason": "uses shaded space at corn base"},
        ],
        "avoid": [
            {"name": "Tomato", "reason": "share corn earworm/tomato fruitworm pest"},
            {"name": "Fennel", "reason": "inhibits corn germination and growth"},
        ],
    },
    {
        "name": "Squash (Cushaw)",
        "category": "vegetable",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 110,
        "notes": "Traditional NM crop. Extremely drought tolerant.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Corn (Heirloom Blue)", "reason": "Three Sisters - squash shades corn roots"},
            {"name": "Pinto Bean", "reason": "Three Sisters - beans fix nitrogen"},
            {"name": "Nasturtium", "reason": "repels squash bugs and cucumber beetles"},
            {"name": "Desert Marigold", "reason": "deters squash vine borers and beetles"},
        ],
        "avoid": [
            {"name": "Potato", "reason": "share blight and vine diseases"},
            {"name": "Fennel", "reason": "allelopathic to cucurbit family"},
        ],
    },

    # --- FRUITS ---
    {
        "name": "Prickly Pear Cactus",
        "category": "fruit",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest", "great_plains", "california", "southeast"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Pads and fruit both edible. Extremely drought tolerant.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Desert Marigold", "reason": "similar water needs, deters soil pests"},
            {"name": "Globe Mallow", "reason": "shares native desert habitat, compatible roots"},
            {"name": "Apache Plume", "reason": "native companion, same low-water conditions"},
        ],
        "avoid": [
            {"name": "Watermelon", "reason": "watermelon irrigation causes cactus root rot"},
            {"name": "Cucumber", "reason": "high water needs incompatible with cactus"},
        ],
    },
    {
        "name": "Apricot",
        "category": "fruit",
        "zones": ["5a","5b","6a","6b","7a","7b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 1095,
        "notes": "Thrives in NM. Late frosts can damage blossoms - plant on a north slope.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Lavender", "reason": "deters pests, attracts pollinators for fruit set"},
            {"name": "Yarrow", "reason": "attracts beneficial predatory insects"},
            {"name": "Chamomile", "reason": "dynamic accumulator, improves soil around roots"},
        ],
        "avoid": [
            {"name": "Tomato", "reason": "shares verticillium wilt pathogen"},
            {"name": "Raspberry", "reason": "shares aphid populations and disease vectors"},
        ],
    },
    {
        "name": "Grape",
        "category": "fruit",
        "zones": ["6a","6b","7a","7b","8a","8b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 1095,
        "notes": "NM has a long winemaking tradition. Well-draining alkaline soil is ideal.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Hyssop", "reason": "traditional companion said to improve grape flavor and growth"},
            {"name": "Chamomile", "reason": "dynamic accumulator, improves soil health"},
            {"name": "Yarrow", "reason": "attracts beneficial insects, deters grape leafhoppers"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic to grape vines"},
            {"name": "Brassicas", "reason": "compete for nutrients and inhibit grape roots"},
        ],
    },

    # --- FLOWERS ---
    {
        "name": "Desert Marigold",
        "category": "flower",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Bright yellow. Blooms spring through fall. Self-seeds readily.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Tomato", "reason": "deters nematodes and whiteflies in soil"},
            {"name": "Green Chile Pepper", "reason": "deters aphids and spider mites"},
            {"name": "Squash (Cushaw)", "reason": "deters squash beetles"},
            {"name": "Pinto Bean", "reason": "deters Mexican bean beetles"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic compounds can affect marigold growth"},
        ],
    },
    {
        "name": "Rocky Mountain Penstemon",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b"],
        "native_regions": ["southwest", "great_plains", "northwest"],
        "water": "low",
        "days_to_maturity": 90,
        "notes": "Attracts hummingbirds. Very drought tolerant once established.",
        "direct_sow": False,
        "weeks_before_frost": 8,
        "companions": [
            {"name": "Yarrow", "reason": "shares low-water habitat, attracts same pollinators"},
            {"name": "Globe Mallow", "reason": "native companion with compatible water needs"},
            {"name": "Apache Plume", "reason": "native shrub companion, similar soil preference"},
        ],
        "avoid": [
            {"name": "Tomato", "reason": "tomato irrigation far exceeds penstemon's drought tolerance"},
            {"name": "Zucchini", "reason": "heavy water and fertilizer needs overwhelm penstemon"},
        ],
    },
    {
        "name": "Zinnia",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Thrives in heat. Direct sow after last frost. Great pollinator plant.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Tomato", "reason": "attracts beneficial insects and pollinators to garden"},
            {"name": "Cucumber", "reason": "draws pollinators that improve cucumber fruit set"},
            {"name": "Corn (Heirloom Blue)", "reason": "fills space at base, attracts pollinators"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic to zinnia"},
        ],
    },
    {
        "name": "Apache Plume",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b"],
        "native_regions": ["southwest", "great_plains"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Feathery seed heads after bloom. Excellent wildlife habitat.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Globe Mallow", "reason": "native desert companions with same water regime"},
            {"name": "Rocky Mountain Penstemon", "reason": "native habitat companions"},
            {"name": "Prickly Pear Cactus", "reason": "shares native xeric habitat"},
        ],
        "avoid": [
            {"name": "Watermelon", "reason": "irrigation demand incompatible with apache plume"},
            {"name": "Swiss Chard", "reason": "chard's water needs cause root problems in apache plume"},
        ],
    },
    {
        "name": "Sunflower",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest", "great_plains", "midwest", "northwest", "california"],
        "water": "low",
        "days_to_maturity": 80,
        "notes": "Native to North America. Direct sow after last frost.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Cucumber", "reason": "shade helps cucumbers, sunflower attracts bees"},
            {"name": "Corn (Heirloom Blue)", "reason": "tall companion, both attract pollinators"},
            {"name": "Desert Marigold", "reason": "combined pest deterrence at garden perimeter"},
        ],
        "avoid": [
            {"name": "Pinto Bean", "reason": "sunflower exudates stunt pole bean growth"},
            {"name": "Potato", "reason": "allelopathic effect on potato tuber development"},
        ],
    },

    # --- VEGETABLES (additional) ---
    {
        "name": "Beet",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 60,
        "notes": "Cool season. Direct sow 4-6 weeks before last frost or in fall. Tolerates light frost. Spring window is short in NM - sow early.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
        "companions": [
            {"name": "Garlic", "reason": "repels pests, enhances beet flavor"},
            {"name": "Onion", "reason": "mutual pest deterrence"},
            {"name": "Lettuce", "reason": "compatible growth habits and timing"},
            {"name": "Chamomile", "reason": "dynamic accumulator that benefits beet soil"},
        ],
        "avoid": [
            {"name": "Pinto Bean", "reason": "pole beans inhibit beet growth"},
            {"name": "Black Bean", "reason": "bean exudates stunt beet development"},
        ],
    },
    {
        "name": "Carrot",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 75,
        "notes": "Direct sow in early spring or fall. Loose, sandy, rock-free soil essential in NM. Thin to 2 inches apart.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
        "companions": [
            {"name": "Onion", "reason": "onion scent confuses carrot fly"},
            {"name": "Leek", "reason": "leek deters carrot fly, carrot deters leek moth"},
            {"name": "Rosemary", "reason": "deters carrot fly with strong scent"},
            {"name": "Tomato", "reason": "tomato repels carrot fly"},
        ],
        "avoid": [
            {"name": "Dill", "reason": "mature dill inhibits carrot growth and crosses"},
            {"name": "Fennel", "reason": "strongly allelopathic to carrots"},
        ],
    },
    {
        "name": "Turnip",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 50,
        "notes": "Cool season. Direct sow in early spring or 8 weeks before first fall frost. Roots and greens both edible.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
        "companions": [
            {"name": "Snap Pea", "reason": "peas fix nitrogen that benefits turnips"},
            {"name": "Nasturtium", "reason": "trap crop for aphids"},
            {"name": "Chamomile", "reason": "improves brassica family growth"},
        ],
        "avoid": [
            {"name": "Kale", "reason": "same family, share clubroot and cabbage moth"},
            {"name": "Fennel", "reason": "allelopathic to brassica family"},
        ],
    },
    {
        "name": "Onion",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 100,
        "notes": "Start indoors 10-12 weeks before last frost or plant sets in early spring. Long-day varieties best at NM elevations above 5000ft.",
        "direct_sow": False,
        "weeks_before_frost": 10,
        "companions": [
            {"name": "Carrot", "reason": "onion scent deters carrot fly, carrot deters onion fly"},
            {"name": "Chamomile", "reason": "said to enhance onion flavor and vigor"},
            {"name": "Beet", "reason": "compatible growth, mutual pest deterrence"},
            {"name": "Tomato", "reason": "onion deters spider mites on tomato"},
        ],
        "avoid": [
            {"name": "Pinto Bean", "reason": "onion inhibits bean germination and growth"},
            {"name": "Snap Pea", "reason": "alliums stunt pea growth"},
            {"name": "Black Bean", "reason": "onion exudates inhibit all legumes"},
        ],
    },
    {
        "name": "Leek",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 120,
        "notes": "Start indoors 10-12 weeks before last frost. Transplant as pencil-thin seedlings. Tolerates frost well - good for NM fall gardens.",
        "direct_sow": False,
        "weeks_before_frost": 12,
        "companions": [
            {"name": "Carrot", "reason": "leek deters carrot fly, carrot deters leek moth"},
            {"name": "Chamomile", "reason": "improves leek vigor"},
            {"name": "Beet", "reason": "compatible companions with similar needs"},
        ],
        "avoid": [
            {"name": "Pinto Bean", "reason": "alliums inhibit legume nitrogen fixation"},
            {"name": "Snap Pea", "reason": "leek stunts pea growth"},
        ],
    },
    {
        "name": "Snap Pea",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 60,
        "notes": "Cool season. Direct sow 4-6 weeks before last frost. Spring window is short in NM - sow as soon as ground is workable.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
        "companions": [
            {"name": "Carrot", "reason": "peas fix nitrogen that feeds carrots"},
            {"name": "Radish", "reason": "radish loosens soil and deters pests"},
            {"name": "Turnip", "reason": "cool season companions with mutual benefit"},
            {"name": "Chamomile", "reason": "attracts beneficial insects"},
        ],
        "avoid": [
            {"name": "Onion", "reason": "alliums inhibit pea growth and root nodules"},
            {"name": "Garlic", "reason": "stunts pea growth and nitrogen fixation"},
            {"name": "Fennel", "reason": "allelopathic to peas"},
        ],
    },
    {
        "name": "Black Bean",
        "category": "vegetable",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 90,
        "notes": "Heat tolerant. Direct sow after last frost. Excellent dry bean for high desert storage. Traditional crop in the SW.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Corn (Heirloom Blue)", "reason": "Three Sisters - corn provides support"},
            {"name": "Squash (Cushaw)", "reason": "Three Sisters - squash shades soil"},
            {"name": "Desert Marigold", "reason": "deters bean beetles"},
            {"name": "Epazote", "reason": "traditional bean companion, repels beetles"},
        ],
        "avoid": [
            {"name": "Onion", "reason": "alliums inhibit bean root nodules"},
            {"name": "Garlic", "reason": "inhibits legume nitrogen fixation"},
        ],
    },
    {
        "name": "Swiss Chard",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 60,
        "notes": "Handles NM summer heat better than most greens. Direct sow after last frost. Cut outer leaves to keep producing all season.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Pinto Bean", "reason": "beans fix nitrogen that benefits chard"},
            {"name": "Onion", "reason": "deters leafminers that attack chard"},
            {"name": "Nasturtium", "reason": "trap crop for aphids"},
            {"name": "Chamomile", "reason": "dynamic accumulator, improves soil"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic, inhibits chard growth"},
        ],
    },
    {
        "name": "Spinach",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 45,
        "notes": "Cool season only - bolts quickly in NM heat. Sow in early spring or fall. Shade cloth extends the season in high desert.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
        "companions": [
            {"name": "Strawberry", "reason": "spinach provides ground cover, both cool season"},
            {"name": "Snap Pea", "reason": "peas fix nitrogen, provide light shade for spinach"},
            {"name": "Radish", "reason": "loosens soil, compatible timing"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic to spinach"},
        ],
    },
    {
        "name": "Arugula",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 40,
        "notes": "Cool season. Bolts quickly in heat. Succession sow every 2 weeks in spring and fall. Excellent cut-and-come-again crop for NM.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
        "companions": [
            {"name": "Tomato", "reason": "tomato canopy provides beneficial shade"},
            {"name": "Snap Pea", "reason": "peas fix nitrogen, cool season timing matches"},
            {"name": "Nasturtium", "reason": "trap crop for aphids that target arugula"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic to arugula"},
            {"name": "Kale", "reason": "same family, share flea beetles and cabbage pests"},
        ],
    },
    {
        "name": "Cucumber",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 55,
        "notes": "Warm season. Direct sow after last frost. Thrives in NM heat with consistent watering. Trellis to save space and improve airflow.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Radish", "reason": "deters cucumber beetles"},
            {"name": "Desert Marigold", "reason": "deters beetles and nematodes in soil"},
            {"name": "Pinto Bean", "reason": "beans fix nitrogen, compatible growth"},
            {"name": "Sunflower", "reason": "sunflower shade reduces cucumber heat stress"},
        ],
        "avoid": [
            {"name": "Sage", "reason": "sage inhibits cucumber growth"},
            {"name": "Potato", "reason": "share blight and beetle pests"},
            {"name": "Fennel", "reason": "allelopathic to cucumber family"},
        ],
    },
    {
        "name": "Radish",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 25,
        "notes": "Fastest vegetable. Direct sow in early spring or fall. Bolts in heat - avoid summer planting in NM. Good row marker for slow crops.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
        "companions": [
            {"name": "Cucumber", "reason": "radish deters cucumber beetles effectively"},
            {"name": "Carrot", "reason": "loosens soil for carrots, compatible timing"},
            {"name": "Snap Pea", "reason": "compatible cool season companions"},
            {"name": "Nasturtium", "reason": "trap crop pairing for aphids"},
        ],
        "avoid": [
            {"name": "Hyssop", "reason": "hyssop exudates inhibit radish germination"},
            {"name": "Fennel", "reason": "allelopathic to radish"},
        ],
    },

    # --- FRUITS (additional) ---
    {
        "name": "Raspberry",
        "category": "fruit",
        "zones": ["5a","5b","6a","6b","7a","7b"],
        "native_regions": ["northeast", "northwest", "great_plains"],
        "water": "medium",
        "days_to_maturity": 365,
        "notes": "Plant bare root canes in early spring. In NM, partial afternoon shade protects from intense sun. Mulch heavily to retain moisture.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Yarrow", "reason": "attracts beneficial predatory insects"},
            {"name": "Chamomile", "reason": "dynamic accumulator, improves soil around canes"},
            {"name": "Desert Marigold", "reason": "deters pests at garden border"},
        ],
        "avoid": [
            {"name": "Tomato", "reason": "shares verticillium wilt pathogen in soil"},
            {"name": "Potato", "reason": "shares blight and verticillium wilt"},
            {"name": "Fennel", "reason": "allelopathic to raspberry canes"},
        ],
    },
    {
        "name": "Strawberry",
        "category": "fruit",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northeast", "northwest", "great_plains", "midwest", "southeast"],
        "water": "medium",
        "days_to_maturity": 365,
        "notes": "Plant crowns in early spring. June-bearing varieties best for NM. Mulch to retain moisture. Everbearing types struggle in high desert heat.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Spinach", "reason": "cool season ground cover, compatible timing"},
            {"name": "Chamomile", "reason": "attracts pollinators, improves strawberry flavor"},
            {"name": "Yarrow", "reason": "attracts beneficial insects for pollination"},
        ],
        "avoid": [
            {"name": "Kale", "reason": "brassicas inhibit strawberry growth"},
            {"name": "Fennel", "reason": "allelopathic to strawberry"},
            {"name": "Tomato", "reason": "shares botrytis and verticillium diseases"},
        ],
    },
    {
        "name": "Watermelon",
        "category": "fruit",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 90,
        "notes": "NM-grown watermelons are exceptional. Start indoors 3-4 weeks before last frost for zone 6b. Needs long warm season and consistent water.",
        "direct_sow": False,
        "weeks_before_frost": 4,
        "companions": [
            {"name": "Nasturtium", "reason": "deters aphids and squash bugs"},
            {"name": "Desert Marigold", "reason": "deters nematodes and beetles in soil"},
            {"name": "Corn (Heirloom Blue)", "reason": "provides windbreak for sprawling vines"},
            {"name": "Radish", "reason": "deters cucumber beetles that attack watermelon"},
        ],
        "avoid": [
            {"name": "Potato", "reason": "shared diseases and space competition"},
            {"name": "Fennel", "reason": "allelopathic to cucurbit family"},
        ],
    },
    {
        "name": "Cantaloupe",
        "category": "fruit",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 80,
        "notes": "NM is renowned for its cantaloupes (especially Pecos Valley). Direct sow after last frost. Reduce water as fruit ripens to concentrate sweetness.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Desert Marigold", "reason": "deters beetles and nematodes"},
            {"name": "Nasturtium", "reason": "trap crop for aphids and cucumber beetles"},
            {"name": "Sunflower", "reason": "attracts pollinators for melon fruit set"},
        ],
        "avoid": [
            {"name": "Potato", "reason": "shared disease susceptibility"},
            {"name": "Fennel", "reason": "allelopathic to melon family"},
        ],
    },
    {
        "name": "Apple",
        "category": "fruit",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a"],
        "native_regions": ["northwest", "northeast"],
        "water": "medium",
        "days_to_maturity": 1095,
        "notes": "Plant bare root in early spring. NM orchards thrive at 5000-7000ft elevation. Need two varieties for cross-pollination. Protect blossoms from late frosts.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Chamomile", "reason": "dynamic accumulator, improves soil under canopy"},
            {"name": "Yarrow", "reason": "attracts beneficial predatory insects"},
            {"name": "Nasturtium", "reason": "trap crop for woolly aphids on apple"},
            {"name": "Lavender", "reason": "deters codling moth and attracts pollinators"},
        ],
        "avoid": [
            {"name": "Potato", "reason": "potato blight can spread to apple fire blight"},
            {"name": "Fennel", "reason": "allelopathic to apple root zone"},
        ],
    },
    {
        "name": "Fig",
        "category": "fruit",
        "zones": ["7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 1095,
        "notes": "Hardy in southern NM. In zone 6b, grow in container or against a south-facing wall. May die back in hard winters but resprouts from roots.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Chamomile", "reason": "dynamic accumulator under fig canopy"},
            {"name": "Desert Marigold", "reason": "deters soil pests around fig roots"},
            {"name": "Lavender", "reason": "same drought-tolerant conditions, deters pests"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic compounds affect fig roots"},
        ],
    },
    {
        "name": "Pomegranate",
        "category": "fruit",
        "zones": ["7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 1095,
        "notes": "Very drought tolerant once established. Thrives in southern NM heat and alkaline soil. Protect from hard freezes below 15F.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Lavender", "reason": "same alkaline, drought-tolerant conditions"},
            {"name": "Desert Marigold", "reason": "native companion, deters pests at base"},
            {"name": "Yarrow", "reason": "attracts beneficial insects for pollination"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic to pomegranate root zone"},
            {"name": "Watermelon", "reason": "irrigation levels incompatible with pomegranate drought preference"},
        ],
    },

    # --- FLOWERS (additional) ---
    {
        "name": "Chamomile",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northwest"],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Direct sow in spring or fall. Self-seeds prolifically. Edible flowers used for tea. German chamomile is annual; Roman is perennial.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Onion", "reason": "enhances onion flavor and growth"},
            {"name": "Garlic", "reason": "said to improve garlic flavor"},
            {"name": "Kale", "reason": "improves brassica vigor as a dynamic accumulator"},
            {"name": "Carrot", "reason": "attracts beneficial hoverflies"},
        ],
        "avoid": [
            {"name": "Mint", "reason": "mint is invasive and will outcompete chamomile"},
        ],
    },
    {
        "name": "Lavender",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northwest"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Thrives in NM alkaline, well-draining soil. Plant after last frost. Spanish lavender (L. stoechas) hardy to zone 6b. Avoid clay soils and overwatering.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Yarrow", "reason": "same low-water conditions, attract same pollinators"},
            {"name": "Echinacea", "reason": "drought-tolerant companions with complementary bloom times"},
            {"name": "Apple", "reason": "deters codling moth, attracts pollinators to orchard"},
            {"name": "Pomegranate", "reason": "same alkaline, drought-tolerant conditions"},
        ],
        "avoid": [
            {"name": "Mint", "reason": "mint requires much more water and will outcompete lavender"},
            {"name": "Spinach", "reason": "incompatible water and soil needs"},
        ],
    },
    {
        "name": "Echinacea",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["great_plains", "midwest", "southeast", "northwest"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Very drought tolerant. Start indoors 8 weeks before last frost. Blooms year 2 from seed. E. angustifolia is the native prairie medicinal species.",
        "direct_sow": False,
        "weeks_before_frost": 8,
        "companions": [
            {"name": "Black-Eyed Susan", "reason": "native prairie companions, bloom together"},
            {"name": "Yarrow", "reason": "attracts same predatory and pollinator insects"},
            {"name": "Lavender", "reason": "drought-tolerant companions with complementary bloom"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic to echinacea"},
        ],
    },
    {
        "name": "Black-Eyed Susan",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["great_plains", "midwest", "northeast", "southeast", "northwest"],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Direct sow in spring. Drought tolerant once established. Self-seeds readily. Attracts pollinators throughout summer.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Echinacea", "reason": "native prairie companions that bloom together"},
            {"name": "Yarrow", "reason": "attracts same beneficial insects and pollinators"},
            {"name": "Cosmos", "reason": "compatible annuals that fill gaps in bloom cycle"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic to black-eyed susan"},
        ],
    },
    {
        "name": "Yarrow",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest", "great_plains", "northwest", "california", "northeast", "midwest", "southeast"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Native across all of North America including NM. Extremely drought tolerant. Spreads by rhizome - give it space. Excellent pollinator plant.",
        "direct_sow": False,
        "weeks_before_frost": 8,
        "companions": [
            {"name": "Echinacea", "reason": "attracts same beneficial insects"},
            {"name": "Lavender", "reason": "low-water companions that share beneficial insect habitat"},
            {"name": "Apple", "reason": "attracts predatory insects that control apple pests"},
            {"name": "Garlic", "reason": "combined insect-attracting and repelling effect"},
        ],
        "avoid": [
            {"name": "Mint", "reason": "mint is invasive and will crowd out yarrow"},
        ],
    },
    {
        "name": "Globe Mallow",
        "category": "flower",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "One of the most drought-tolerant flowering plants for NM. Orange blooms spring through fall. Direct sow in fall for natural cold stratification.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Desert Marigold", "reason": "native companions with identical water needs"},
            {"name": "Apache Plume", "reason": "shares native xeric habitat"},
            {"name": "Prickly Pear Cactus", "reason": "compatible desert habitat companions"},
        ],
        "avoid": [
            {"name": "Watermelon", "reason": "irrigation levels incompatible with globe mallow"},
            {"name": "Cucumber", "reason": "cucumber water needs will cause root rot in globe mallow"},
        ],
    },
    {
        "name": "Clarkia",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["california", "northwest"],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Cool season annual. Direct sow in fall or early spring in NM. Does well in partial shade in high desert. Showy blooms before summer heat arrives.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Snap Pea", "reason": "cool season companions that overlap in timing"},
            {"name": "Chamomile", "reason": "compatible cool season annuals"},
            {"name": "Spinach", "reason": "cool season companions sharing partial shade"},
        ],
        "avoid": [
            {"name": "Zinnia", "reason": "clarkia dies back before zinnia thrives - timing conflict"},
            {"name": "Fennel", "reason": "allelopathic to clarkia"},
        ],
    },
    {
        "name": "Cosmos",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Direct sow after last frost. Thrives on neglect - too much water reduces blooms. Self-seeds readily. Excellent in NM summer heat.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Tomato", "reason": "attracts beneficial hoverflies and wasps"},
            {"name": "Corn (Heirloom Blue)", "reason": "fills base space, attracts pollinators"},
            {"name": "Black-Eyed Susan", "reason": "compatible warm season annuals that attract same insects"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic to cosmos"},
        ],
    },
    {
        "name": "Hollyhock",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Classic NM cottage garden plant. Biennial - blooms year 2. Drought tolerant once established. Self-seeds prolifically along walls and fences.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Sunflower", "reason": "tall companions that share wind and visual structure"},
            {"name": "Desert Marigold", "reason": "deters pests at base of hollyhock"},
            {"name": "Yarrow", "reason": "attracts beneficial insects to the bed"},
        ],
        "avoid": [
            {"name": "Tomato", "reason": "hollyhock can harbor rust that spreads to nightshades"},
            {"name": "Green Chile Pepper", "reason": "hollyhock rust risk to pepper plants"},
        ],
    },
    {
        "name": "Four O'Clock",
        "category": "flower",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Mirabilis multiflora (Desert Four O'Clock) is native to NM. Tuberous root survives drought. Direct sow after last frost. Magenta blooms attract moths.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Corn (Heirloom Blue)", "reason": "trap crop for Japanese beetle larvae near corn"},
            {"name": "Desert Marigold", "reason": "native companions with compatible water needs"},
            {"name": "Globe Mallow", "reason": "shares native xeric SW habitat"},
        ],
        "avoid": [
            {"name": "Edibles (general)", "reason": "all parts of four o'clock are toxic - keep away from food garden areas"},
        ],
    },

    # --- HERBS ---
    {
        "name": "Cilantro",
        "category": "herb",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 45,
        "notes": "Cool season only - bolts quickly in NM heat. Succession sow every 2-3 weeks in spring and fall. Let bolt for coriander seed harvest.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Spinach", "reason": "cool season companions with similar needs"},
            {"name": "Snap Pea", "reason": "cool season timing match, peas fix nitrogen"},
            {"name": "Tomato", "reason": "bolted cilantro attracts beneficial wasps and hoverflies"},
            {"name": "Carrot", "reason": "same family when bolted, attracts same beneficial insects"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "fennel inhibits cilantro and they cross-pollinate"},
            {"name": "Lavender", "reason": "incompatible water needs, lavender dries out too fast"},
        ],
    },
    {
        "name": "Epazote",
        "category": "herb",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Traditional NM/Mexican herb used with beans. Extremely heat and drought tolerant. Direct sow after last frost. Self-seeds aggressively.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Pinto Bean", "reason": "traditional companion - repels bean beetles, aids digestion"},
            {"name": "Black Bean", "reason": "traditional bean companion across SW and Mesoamerica"},
            {"name": "Corn (Heirloom Blue)", "reason": "companion in traditional Three Sisters + epazote plots"},
            {"name": "Green Chile Pepper", "reason": "traditional NM kitchen garden pairing"},
        ],
        "avoid": [
            {"name": "Snap Pea", "reason": "epazote can inhibit legumes other than dry beans"},
        ],
    },
    {
        "name": "Mexican Oregano",
        "category": "herb",
        "zones": ["7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Not related to Mediterranean oregano. Stronger, more citrusy flavor - core herb in NM cuisine. Hardy perennial shrub. Grow in container in zone 6b.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Green Chile Pepper", "reason": "enhances pepper flavor, deters aphids"},
            {"name": "Tomato", "reason": "deters spider mites, compatible water needs when established"},
            {"name": "Pinto Bean", "reason": "traditional NM garden pairing, repels bean pests"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic to oregano, cross-flavor contamination"},
        ],
    },
    {
        "name": "Culantro",
        "category": "herb",
        "zones": ["7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 70,
        "notes": "Tropical herb with bold cilantro flavor that doesn't bolt in heat - excellent NM summer alternative to cilantro. Needs partial shade. Start indoors 6-8 weeks before last frost.",
        "direct_sow": False,
        "weeks_before_frost": 8,
        "companions": [
            {"name": "Tomato", "reason": "tomato canopy provides partial shade culantro needs"},
            {"name": "Pinto Bean", "reason": "similar to cilantro, attracts same beneficial insects"},
            {"name": "Swiss Chard", "reason": "compatible water needs, both enjoy partial shade"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic and cross-contaminates flavor"},
        ],
    },
    {
        "name": "Hyssop",
        "category": "herb",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest", "great_plains"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Agastache (hummingbird mint) species are native to NM and extremely drought tolerant. Attracts hummingbirds and pollinators. Start indoors 8 weeks before last frost.",
        "direct_sow": False,
        "weeks_before_frost": 8,
        "companions": [
            {"name": "Grape", "reason": "traditional companion said to improve grape flavor and vigor"},
            {"name": "Yarrow", "reason": "low-water companions that share hummingbird and pollinator habitat"},
            {"name": "Echinacea", "reason": "compatible drought-tolerant perennials"},
        ],
        "avoid": [
            {"name": "Radish", "reason": "hyssop exudates inhibit radish germination"},
            {"name": "Fennel", "reason": "allelopathic to hyssop"},
        ],
    },

    # --- PNW / ZONE 8b-9a ADDITIONS ---
    {
        "name": "Blueberry",
        "category": "fruit",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a"],
        "native_regions": ["northwest", "northeast", "southeast"],
        "water": "medium",
        "days_to_maturity": 730,
        "notes": "Thrives in PNW acidic, well-drained soil (pH 4.5-5.5). Highbush varieties excel in western Washington. Plant two varieties for cross-pollination. Amend with sulfur if soil pH is too high.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Rhododendron", "reason": "share acidic soil preference, compatible root zones"},
            {"name": "Strawberry", "reason": "ground cover that shares moisture and acid soil needs"},
            {"name": "Chamomile", "reason": "attracts pollinators critical for berry set"},
        ],
        "avoid": [
            {"name": "Tomato", "reason": "nightshades prefer alkaline soil, competes poorly near blueberries"},
            {"name": "Fennel", "reason": "allelopathic, inhibits blueberry growth"},
        ],
    },
    {
        "name": "Rhododendron",
        "category": "flower",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northwest", "california"],
        "water": "medium",
        "days_to_maturity": 730,
        "notes": "State flower of Washington. Thrives in PNW dappled shade with moist, acidic soil (pH 4.5-6.0). R. macrophyllum is the native species. Avoid planting in full sun or dry sites. Mulch heavily to retain moisture.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Blueberry", "reason": "share acidic soil preference, similar moisture needs"},
            {"name": "Sword Fern", "reason": "native understory companions that share woodland conditions"},
            {"name": "Oregon Grape", "reason": "native acidic-soil companions, similar light requirements"},
        ],
        "avoid": [
            {"name": "Lavender", "reason": "lavender prefers alkaline, dry soil — opposite of rhododendron needs"},
            {"name": "Garlic", "reason": "alliums disrupt shallow rhododendron root systems"},
        ],
    },
    {
        "name": "Salal",
        "category": "fruit",
        "zones": ["7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northwest", "california"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Native PNW groundcover with edible dark berries. Extremely shade tolerant — thrives under conifers where little else grows. Berries ripen August-September. Important food source for wildlife. Spreads slowly by rhizome.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Sword Fern", "reason": "native forest floor companions with identical light and moisture needs"},
            {"name": "Oregon Grape", "reason": "co-evolved native understory plants"},
            {"name": "Rhododendron", "reason": "share acidic woodland conditions"},
        ],
        "avoid": [
            {"name": "Lavender", "reason": "needs opposite conditions — full sun and dry soil"},
            {"name": "Tomato", "reason": "incompatible sun and soil requirements"},
        ],
    },
    {
        "name": "Sword Fern",
        "category": "flower",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northwest", "california"],
        "water": "medium",
        "days_to_maturity": 365,
        "notes": "The quintessential PNW native fern (Polystichum munitum). Evergreen, deer resistant, and thrives in deep shade under conifers. Excellent for shady borders. Plant in well-amended, moist soil. Drought tolerant once established.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Salal", "reason": "native forest floor companions"},
            {"name": "Oregon Grape", "reason": "co-evolved PNW understory plants"},
            {"name": "Rhododendron", "reason": "thrives in same shaded, acidic conditions"},
        ],
        "avoid": [
            {"name": "Lavender", "reason": "needs full sun and dry conditions, opposite to fern"},
            {"name": "Sunflower", "reason": "full sun plants compete poorly in the shade ferns prefer"},
        ],
    },
    {
        "name": "Oregon Grape",
        "category": "fruit",
        "zones": ["5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northwest", "california"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Native PNW evergreen shrub (Mahonia aquifolium) — state flower of Oregon. Tart blue-purple berries ripen in summer, excellent for jam. Tolerates deep shade and dry conditions once established. Holly-like leaves turn bronze in winter.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Sword Fern", "reason": "co-evolved native understory companions"},
            {"name": "Salal", "reason": "native forest companions with similar shade tolerance"},
            {"name": "Rhododendron", "reason": "share acidic, woodland soil conditions"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic, inhibits most nearby shrubs"},
            {"name": "Tomato", "reason": "incompatible sun and soil requirements"},
        ],
    },
    {
        "name": "Huckleberry",
        "category": "fruit",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a"],
        "native_regions": ["northwest", "california", "northeast"],
        "water": "medium",
        "days_to_maturity": 730,
        "notes": "Native PNW shrub (Vaccinium parvifolium and others). Highly prized tart berries ripen July-August. Requires acidic soil (pH 4.5-5.5) and cool roots. Difficult to transplant from wild — purchase nursery stock. Slow to establish but long-lived.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Blueberry", "reason": "closely related, share acidic soil and moisture needs"},
            {"name": "Rhododendron", "reason": "share acidic woodland conditions"},
            {"name": "Salal", "reason": "native companions that thrive in same forest edge habitat"},
        ],
        "avoid": [
            {"name": "Lavender", "reason": "needs alkaline dry soil, opposite of huckleberry requirements"},
            {"name": "Garlic", "reason": "alliums disrupt shallow berry shrub root systems"},
        ],
    },
    {
        "name": "Dahlia",
        "category": "flower",
        "zones": ["7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northwest"],
        "water": "medium",
        "days_to_maturity": 90,
        "notes": "PNW is world-famous for dahlias — Seattle's climate produces exceptional blooms. Plant tubers after soil reaches 60°F (mid-May in zone 8b). Pinch early for bushy plants. Dig and store tubers in zones below 8a after first frost.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Chamomile", "reason": "attracts beneficial insects that reduce aphid pressure on dahlias"},
            {"name": "Nasturtium", "reason": "trap crop for aphids, keeps them off dahlia stems"},
            {"name": "Yarrow", "reason": "attracts predatory wasps that control earwigs"},
        ],
        "avoid": [
            {"name": "Fennel", "reason": "allelopathic, stunts nearby plants including dahlias"},
            {"name": "Garlic", "reason": "some evidence alliums inhibit dahlia tuber development"},
        ],
    },
    {
        "name": "Fuchsia",
        "category": "flower",
        "zones": ["8a","8b","9a","9b"],
        "native_regions": ["northwest"],
        "water": "high",
        "days_to_maturity": 60,
        "notes": "Iconic PNW hanging basket plant. Thrives in cool, moist PNW summers — struggles in hot dry climates. Hardy fuchsias (F. magellanica) can overwinter in zone 8b+. Hummingbird magnet. Bring tender varieties indoors before first frost.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Chamomile", "reason": "attracts pollinators that also visit fuchsia"},
            {"name": "Sword Fern", "reason": "shade companions with similar moisture needs"},
        ],
        "avoid": [
            {"name": "Lavender", "reason": "fuchsia needs high moisture and shade — opposite of lavender"},
            {"name": "Sunflower", "reason": "tall sunflowers compete for light and dry out soil"},
        ],
    },
    {
        "name": "Bleeding Heart",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a"],
        "native_regions": ["northwest", "california"],
        "water": "medium",
        "days_to_maturity": 365,
        "notes": "Pacific Bleeding Heart (Dicentra formosa) is native to PNW forests. Heart-shaped pink flowers spring through summer. Goes dormant in summer heat — plant with late-emerging perennials to fill the gap. Thrives in moist woodland shade.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Sword Fern", "reason": "native woodland companions that share dappled shade"},
            {"name": "Salal", "reason": "fills in when bleeding heart goes dormant in summer"},
            {"name": "Chamomile", "reason": "self-seeds to fill gaps when bleeding heart dies back"},
        ],
        "avoid": [
            {"name": "Lavender", "reason": "needs opposite conditions — full sun and dry soil"},
            {"name": "Sunflower", "reason": "heavy feeders that dry soil and compete for light"},
        ],
    },
    {
        "name": "Foxglove",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northwest"],
        "water": "medium",
        "days_to_maturity": 365,
        "notes": "Naturalized throughout PNW — a signature plant of western Washington roadsides and woodland edges. Biennial: grows foliage year 1, blooms year 2. Direct sow in fall or early spring. Self-seeds prolifically. All parts toxic — wear gloves when handling.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Apple", "reason": "said to improve disease resistance of nearby apple trees"},
            {"name": "Rhododendron", "reason": "share woodland edge conditions and acidic soil"},
            {"name": "Yarrow", "reason": "tall companions that share semi-shaded borders"},
        ],
        "avoid": [
            {"name": "Tomato", "reason": "foxglove can harbor similar viral diseases"},
        ],
    },
    {
        "name": "Rhubarb",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a"],
        "native_regions": ["northwest"],
        "water": "medium",
        "days_to_maturity": 730,
        "notes": "Thrives in cool PNW climate — one of the easiest crops in western Washington. Plant crowns in early spring. Do not harvest stalks in year 1. Leaves are toxic; stalks only are edible. Divide crowns every 4-5 years to maintain vigor.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Strawberry", "reason": "classic pairing — share moisture needs and deter similar pests"},
            {"name": "Chamomile", "reason": "attracts beneficial insects near rhubarb"},
            {"name": "Garlic", "reason": "deters aphids and rhubarb curculio"},
        ],
        "avoid": [
            {"name": "Tomato", "reason": "both susceptible to verticillium wilt, increase disease pressure"},
            {"name": "Corn (Heirloom Blue)", "reason": "heavy feeders that compete with rhubarb for nutrients"},
        ],
    },
    {
        "name": "Nasturtium",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northwest"],
        "water": "low",
        "days_to_maturity": 55,
        "notes": "Fast-growing edible annual — flowers, leaves, and seeds all edible with peppery flavor. Direct sow after last frost. Thrives in PNW cool summers. Excellent trap crop for aphids. Do not over-fertilize — excess nitrogen reduces flowering.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Tomato", "reason": "trap crop for aphids and whiteflies, lures them away from tomatoes"},
            {"name": "Zucchini", "reason": "trap crop for squash aphids and cucumber beetles"},
            {"name": "Dahlia", "reason": "trap crop keeps aphids off dahlia stems"},
            {"name": "Apple", "reason": "repels woolly aphids from apple tree bases"},
        ],
        "avoid": [
            {"name": "Cauliflower", "reason": "nasturtiums attract cabbage white butterflies toward brassicas"},
        ],
    },
    {
        "name": "Pacific Coast Iris",
        "category": "flower",
        "zones": ["7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northwest", "california"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Native iris of the PNW coast and California ranges (Iris douglasiana and hybrids). Blooms April-May in stunning purples, blues, and creams. Extremely drought tolerant once established — do not overwater in summer. Resents root disturbance; plant and leave.",
        "direct_sow": False,
        "weeks_before_frost": 0,
        "companions": [
            {"name": "Oregon Grape", "reason": "co-native low-water plants that share woodland edge habitat"},
            {"name": "Salal", "reason": "native groundcover that complements iris without competing"},
            {"name": "Yarrow", "reason": "low-water companions that share well-drained sunny borders"},
        ],
        "avoid": [
            {"name": "Tomato", "reason": "tomatoes require regular heavy watering that rots iris rhizomes"},
            {"name": "Zucchini", "reason": "large leaves shade out low-growing iris"},
        ],
    },
]

def get_plants_for_zone(zone):
    """Returns all plants compatible with the given zone."""
    return [p for p in PLANTS if zone in p["zones"]]

def group_by_category(plants):
    """Groups a list of plants into a dict by category."""
    grouped = {}
    for plant in plants:
        cat = plant["category"]
        if cat not in grouped:
            grouped[cat] = []
        grouped[cat].append(plant)
    return grouped

def is_native_to_region(plant, region):
    """Returns True if the plant is native to the given region."""
    return region in plant.get("native_regions", [])

def state_to_region(state_name):
    """Maps a US state name to one of seven regions."""
    mapping = {
        "Alabama": "southeast",
        "Alaska": "northwest",
        "Arizona": "southwest",
        "Arkansas": "southeast",
        "California": "california",
        "Colorado": "southwest",
        "Connecticut": "northeast",
        "Delaware": "northeast",
        "Florida": "southeast",
        "Georgia": "southeast",
        "Hawaii": "california",
        "Idaho": "northwest",
        "Illinois": "midwest",
        "Indiana": "midwest",
        "Iowa": "midwest",
        "Kansas": "great_plains",
        "Kentucky": "southeast",
        "Louisiana": "southeast",
        "Maine": "northeast",
        "Maryland": "northeast",
        "Massachusetts": "northeast",
        "Michigan": "midwest",
        "Minnesota": "midwest",
        "Mississippi": "southeast",
        "Missouri": "midwest",
        "Montana": "great_plains",
        "Nebraska": "great_plains",
        "Nevada": "southwest",
        "New Hampshire": "northeast",
        "New Jersey": "northeast",
        "New Mexico": "southwest",
        "New York": "northeast",
        "North Carolina": "southeast",
        "North Dakota": "great_plains",
        "Ohio": "midwest",
        "Oklahoma": "great_plains",
        "Oregon": "northwest",
        "Pennsylvania": "northeast",
        "Rhode Island": "northeast",
        "South Carolina": "southeast",
        "South Dakota": "great_plains",
        "Tennessee": "southeast",
        "Texas": "great_plains",
        "Utah": "southwest",
        "Vermont": "northeast",
        "Virginia": "southeast",
        "Washington": "northwest",
        "West Virginia": "southeast",
        "Wisconsin": "midwest",
        "Wyoming": "great_plains",
    }
    return mapping.get(state_name)
