# Plant database for zones 5a through 9b
# native_regions: list of US regions where the plant is actually native
#   regions: southwest, great_plains, northeast, southeast, midwest, northwest, california
# water: low / medium / high
# days_to_maturity: approximate days from transplant (or seed where noted)

PLANTS = [
    # --- VEGETABLES ---
    {
        "name": "Green Chile Pepper",
        "category": "vegetable",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "medium",
        "days_to_maturity": 80,
        "notes": "Staple of NM cuisine. Start indoors 8 weeks before last frost.",
        "direct_sow": False,
        "weeks_before_frost": 8,
    },
    {
        "name": "Pinto Bean",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 90,
        "notes": "Heat tolerant. Direct sow after last frost.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Tomato",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 70,
        "notes": "Start indoors 6-8 weeks before last frost. Mulch heavily in NM heat.",
        "direct_sow": False,
        "weeks_before_frost": 8,
    },
    {
        "name": "Zucchini",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 50,
        "notes": "Direct sow after last frost. Very productive in high desert.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Garlic",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 240,
        "notes": "Plant cloves in fall (Oct-Nov) for summer harvest.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Kale",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 55,
        "notes": "Cold hardy. Can overwinter in zone 6b with light protection.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
    },
    {
        "name": "Corn (Heirloom Blue)",
        "category": "vegetable",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest", "great_plains", "midwest", "northeast", "southeast"],
        "water": "medium",
        "days_to_maturity": 100,
        "notes": "Traditional Pueblo crop. Direct sow in blocks for pollination.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Squash (Cushaw)",
        "category": "vegetable",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 110,
        "notes": "Traditional NM crop. Extremely drought tolerant.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },

    # --- FRUITS ---
    {
        "name": "Prickly Pear Cactus",
        "category": "fruit",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest", "great_plains", "california", "southeast"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Pads and fruit both edible. Extremely drought tolerant.",
        "direct_sow": False,
        "weeks_before_frost": 0,
    },
    {
        "name": "Apricot",
        "category": "fruit",
        "zones": ["5a","5b","6a","6b","7a","7b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 1095,
        "notes": "Thrives in NM. Late frosts can damage blossoms - plant on a north slope.",
        "direct_sow": False,
        "weeks_before_frost": 0,
    },
    {
        "name": "Grape",
        "category": "fruit",
        "zones": ["6a","6b","7a","7b","8a","8b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 1095,
        "notes": "NM has a long winemaking tradition. Well-draining alkaline soil is ideal.",
        "direct_sow": False,
        "weeks_before_frost": 0,
    },

    # --- FLOWERS ---
    {
        "name": "Desert Marigold",
        "category": "flower",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Bright yellow. Blooms spring through fall. Self-seeds readily.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Rocky Mountain Penstemon",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b"],
        "native_regions": ["southwest", "great_plains", "northwest"],
        "water": "low",
        "days_to_maturity": 90,
        "notes": "Attracts hummingbirds. Very drought tolerant once established.",
        "direct_sow": False,
        "weeks_before_frost": 8,
    },
    {
        "name": "Zinnia",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Thrives in heat. Direct sow after last frost. Great pollinator plant.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Apache Plume",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b"],
        "native_regions": ["southwest", "great_plains"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Feathery seed heads after bloom. Excellent wildlife habitat.",
        "direct_sow": False,
        "weeks_before_frost": 0,
    },
    {
        "name": "Sunflower",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest", "great_plains", "midwest", "northwest", "california"],
        "water": "low",
        "days_to_maturity": 80,
        "notes": "Native to North America. Direct sow after last frost.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },

    # --- VEGETABLES (additional) ---
    {
        "name": "Beet",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 60,
        "notes": "Cool season. Direct sow 4-6 weeks before last frost or in fall. Tolerates light frost. Spring window is short in NM - sow early.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
    },
    {
        "name": "Carrot",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 75,
        "notes": "Direct sow in early spring or fall. Loose, sandy, rock-free soil essential in NM. Thin to 2 inches apart.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
    },
    {
        "name": "Turnip",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 50,
        "notes": "Cool season. Direct sow in early spring or 8 weeks before first fall frost. Roots and greens both edible.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
    },
    {
        "name": "Onion",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 100,
        "notes": "Start indoors 10-12 weeks before last frost or plant sets in early spring. Long-day varieties best at NM elevations above 5000ft.",
        "direct_sow": False,
        "weeks_before_frost": 10,
    },
    {
        "name": "Leek",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 120,
        "notes": "Start indoors 10-12 weeks before last frost. Transplant as pencil-thin seedlings. Tolerates frost well - good for NM fall gardens.",
        "direct_sow": False,
        "weeks_before_frost": 12,
    },
    {
        "name": "Snap Pea",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 60,
        "notes": "Cool season. Direct sow 4-6 weeks before last frost. Spring window is short in NM - sow as soon as ground is workable.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
    },
    {
        "name": "Black Bean",
        "category": "vegetable",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 90,
        "notes": "Heat tolerant. Direct sow after last frost. Excellent dry bean for high desert storage. Traditional crop in the SW.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Swiss Chard",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 60,
        "notes": "Handles NM summer heat better than most greens. Direct sow after last frost. Cut outer leaves to keep producing all season.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Spinach",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 45,
        "notes": "Cool season only - bolts quickly in NM heat. Sow in early spring or fall. Shade cloth extends the season in high desert.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
    },
    {
        "name": "Arugula",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 40,
        "notes": "Cool season. Bolts quickly in heat. Succession sow every 2 weeks in spring and fall. Excellent cut-and-come-again crop for NM.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
    },
    {
        "name": "Cucumber",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 55,
        "notes": "Warm season. Direct sow after last frost. Thrives in NM heat with consistent watering. Trellis to save space and improve airflow.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Radish",
        "category": "vegetable",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 25,
        "notes": "Fastest vegetable. Direct sow in early spring or fall. Bolts in heat - avoid summer planting in NM. Good row marker for slow crops.",
        "direct_sow": True,
        "weeks_before_frost": 0,
        "cool_season": True,
    },

    # --- FRUITS (additional) ---
    {
        "name": "Raspberry",
        "category": "fruit",
        "zones": ["5a","5b","6a","6b","7a","7b"],
        "native_regions": ["northeast", "northwest", "great_plains"],
        "water": "medium",
        "days_to_maturity": 365,
        "notes": "Plant bare root canes in early spring. In NM, partial afternoon shade protects from intense sun. Mulch heavily to retain moisture.",
        "direct_sow": False,
        "weeks_before_frost": 0,
    },
    {
        "name": "Strawberry",
        "category": "fruit",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["northeast", "northwest", "great_plains", "midwest", "southeast"],
        "water": "medium",
        "days_to_maturity": 365,
        "notes": "Plant crowns in early spring. June-bearing varieties best for NM. Mulch to retain moisture. Everbearing types struggle in high desert heat.",
        "direct_sow": False,
        "weeks_before_frost": 0,
    },
    {
        "name": "Watermelon",
        "category": "fruit",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 90,
        "notes": "NM-grown watermelons are exceptional. Start indoors 3-4 weeks before last frost for zone 6b. Needs long warm season and consistent water.",
        "direct_sow": False,
        "weeks_before_frost": 4,
    },
    {
        "name": "Cantaloupe",
        "category": "fruit",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 80,
        "notes": "NM is renowned for its cantaloupes (especially Pecos Valley). Direct sow after last frost. Reduce water as fruit ripens to concentrate sweetness.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Apple",
        "category": "fruit",
        "zones": ["5a","5b","6a","6b","7a","7b","8a"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 1095,
        "notes": "Plant bare root in early spring. NM orchards thrive at 5000-7000ft elevation. Need two varieties for cross-pollination. Protect blossoms from late frosts.",
        "direct_sow": False,
        "weeks_before_frost": 0,
    },
    {
        "name": "Fig",
        "category": "fruit",
        "zones": ["7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 1095,
        "notes": "Hardy in southern NM. In zone 6b, grow in container or against a south-facing wall. May die back in hard winters but resprouts from roots.",
        "direct_sow": False,
        "weeks_before_frost": 0,
    },
    {
        "name": "Pomegranate",
        "category": "fruit",
        "zones": ["7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 1095,
        "notes": "Very drought tolerant once established. Thrives in southern NM heat and alkaline soil. Protect from hard freezes below 15F.",
        "direct_sow": False,
        "weeks_before_frost": 0,
    },

    # --- FLOWERS (additional) ---
    {
        "name": "Chamomile",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Direct sow in spring or fall. Self-seeds prolifically. Edible flowers used for tea. German chamomile is annual; Roman is perennial.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Lavender",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Thrives in NM alkaline, well-draining soil. Plant after last frost. Spanish lavender (L. stoechas) hardy to zone 6b. Avoid clay soils and overwatering.",
        "direct_sow": False,
        "weeks_before_frost": 0,
    },
    {
        "name": "Echinacea",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["great_plains", "midwest", "southeast"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Very drought tolerant. Start indoors 8 weeks before last frost. Blooms year 2 from seed. E. angustifolia is the native prairie medicinal species.",
        "direct_sow": False,
        "weeks_before_frost": 8,
    },
    {
        "name": "Black-Eyed Susan",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["great_plains", "midwest", "northeast", "southeast"],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Direct sow in spring. Drought tolerant once established. Self-seeds readily. Attracts pollinators throughout summer.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Yarrow",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest", "great_plains", "northwest", "california", "northeast", "midwest", "southeast"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Native across all of North America including NM. Extremely drought tolerant. Spreads by rhizome - give it space. Excellent pollinator plant.",
        "direct_sow": False,
        "weeks_before_frost": 8,
    },
    {
        "name": "Globe Mallow",
        "category": "flower",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "One of the most drought-tolerant flowering plants for NM. Orange blooms spring through fall. Direct sow in fall for natural cold stratification.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Clarkia",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["california", "northwest"],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Cool season annual. Direct sow in fall or early spring in NM. Does well in partial shade in high desert. Showy blooms before summer heat arrives.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Cosmos",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Direct sow after last frost. Thrives on neglect - too much water reduces blooms. Self-seeds readily. Excellent in NM summer heat.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Hollyhock",
        "category": "flower",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Classic NM cottage garden plant. Biennial - blooms year 2. Drought tolerant once established. Self-seeds prolifically along walls and fences.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Four O'Clock",
        "category": "flower",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Mirabilis multiflora (Desert Four O'Clock) is native to NM. Tuberous root survives drought. Direct sow after last frost. Magenta blooms attract moths.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },

    # --- HERBS ---
    {
        "name": "Cilantro",
        "category": "herb",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 45,
        "notes": "Cool season only - bolts quickly in NM heat. Succession sow every 2-3 weeks in spring and fall. Let bolt for coriander seed harvest.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Epazote",
        "category": "herb",
        "zones": ["6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 60,
        "notes": "Traditional NM/Mexican herb used with beans. Extremely heat and drought tolerant. Direct sow after last frost. Self-seeds aggressively.",
        "direct_sow": True,
        "weeks_before_frost": 0,
    },
    {
        "name": "Mexican Oregano",
        "category": "herb",
        "zones": ["7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Not related to Mediterranean oregano. Stronger, more citrusy flavor - core herb in NM cuisine. Hardy perennial shrub. Grow in container in zone 6b.",
        "direct_sow": False,
        "weeks_before_frost": 0,
    },
    {
        "name": "Culantro",
        "category": "herb",
        "zones": ["7a","7b","8a","8b","9a","9b"],
        "native_regions": [],
        "water": "medium",
        "days_to_maturity": 70,
        "notes": "Tropical herb with bold cilantro flavor that doesn't bolt in heat - excellent NM summer alternative to cilantro. Needs partial shade. Start indoors 6-8 weeks before last frost.",
        "direct_sow": False,
        "weeks_before_frost": 8,
    },
    {
        "name": "Hyssop",
        "category": "herb",
        "zones": ["5a","5b","6a","6b","7a","7b","8a","8b","9a","9b"],
        "native_regions": ["southwest", "great_plains"],
        "water": "low",
        "days_to_maturity": 365,
        "notes": "Agastache (hummingbird mint) species are native to NM and extremely drought tolerant. Attracts hummingbirds and pollinators. Start indoors 8 weeks before last frost.",
        "direct_sow": False,
        "weeks_before_frost": 8,
    },
]

def get_plants_for_zone(zone):
    """Returns all plants compatible with the given zone."""
    return [p for p in PLANTS if zone in p["zones"]]

def group_by_category(plants):
    """Groups a list of plants into a dict by category."""
    grouped = {}
    for plant in plants:
        cat = plant["category"]
        if cat not in grouped:
            grouped[cat] = []
        grouped[cat].append(plant)
    return grouped

def is_native_to_region(plant, region):
    """Returns True if the plant is native to the given region."""
    return region in plant.get("native_regions", [])

def state_to_region(state_name):
    """Maps a US state name to one of seven regions."""
    mapping = {
        "Alabama": "southeast",
        "Alaska": "northwest",
        "Arizona": "southwest",
        "Arkansas": "southeast",
        "California": "california",
        "Colorado": "southwest",
        "Connecticut": "northeast",
        "Delaware": "northeast",
        "Florida": "southeast",
        "Georgia": "southeast",
        "Hawaii": "california",
        "Idaho": "northwest",
        "Illinois": "midwest",
        "Indiana": "midwest",
        "Iowa": "midwest",
        "Kansas": "great_plains",
        "Kentucky": "southeast",
        "Louisiana": "southeast",
        "Maine": "northeast",
        "Maryland": "northeast",
        "Massachusetts": "northeast",
        "Michigan": "midwest",
        "Minnesota": "midwest",
        "Mississippi": "southeast",
        "Missouri": "midwest",
        "Montana": "great_plains",
        "Nebraska": "great_plains",
        "Nevada": "southwest",
        "New Hampshire": "northeast",
        "New Jersey": "northeast",
        "New Mexico": "southwest",
        "New York": "northeast",
        "North Carolina": "southeast",
        "North Dakota": "great_plains",
        "Ohio": "midwest",
        "Oklahoma": "great_plains",
        "Oregon": "northwest",
        "Pennsylvania": "northeast",
        "Rhode Island": "northeast",
        "South Carolina": "southeast",
        "South Dakota": "great_plains",
        "Tennessee": "southeast",
        "Texas": "great_plains",
        "Utah": "southwest",
        "Vermont": "northeast",
        "Virginia": "southeast",
        "Washington": "northwest",
        "West Virginia": "southeast",
        "Wisconsin": "midwest",
        "Wyoming": "great_plains",
    }
    return mapping.get(state_name)
